### ISSUE TITLE
rdp_check OpenSSL.SSL.WantReadError

### ISSUE THREAD

**Issue by CptGuo** [fortra/impacket#1007]
### Configuration  
impacket version:  latest
Python version:  3.8.5
Target OS:  Windows 2018
### Debug Output With Command String  
Traceback (most recent call last):
  File "/home/py/pwd-cracknode/pwd-cracker/src/test/rdp.py", line 578, in <module>
    check_rdp("147.230.11.51", 3389, "admin", "admin", "", hashes=None)
  File "/home//py/pwd-cracknode/pwd-cracker/src/test/rdp.py", line 408, in check_rdp
    tls.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

### PCAP  
If applicable, add a packet capture to help explain your problem.

### Additional context  
Space for additional context, investigative results, suspected issue.

**Comment by ljluestc** [comment]
```
from OpenSSL import SSL
import select
import socket

def check_rdp(host, port, username, password, domain='', hashes=None):
    # Assuming this is how you initialize your TLS context
    ctx = SSL.Context(SSL.TLSv1_2_METHOD)  # Adjust according to your needs
    
    # Create a socket and wrap it with SSL
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setblocking(0)  # Set as non-blocking
    
    try:
        sock.connect((host, port))
    except BlockingIOError:
        # Connection in progress, wait for it
        select.select([], [sock], [], 5)  # Wait up to 5 seconds for connection

    tls = SSL.Connection(ctx, sock)
    try:
        while True:
            try:
                tls.do_handshake()
                # If we make it here, handshake is done
                break
            except SSL.WantReadError:
                # Wait for data to be available to read
                select.select([sock], [], [], 5)
            except SSL.WantWriteError:
                # Wait for data to be written
                select.select([], [sock], [], 5)
    except Exception as e:
        print(f"Handshake failed: {e}")
        return False

    # Continue with RDP authentication logic here
    # ...

    # Example: Send some data, receive the response, etc.
    try:
        # Here would be the logic for RDP protocol, authentication, etc.
        pass
    except Exception as e:
        print(f"RDP operation failed: {e}")
        return False
    finally:
        tls.shutdown()
        sock.close()

    return True  # If all went well

# Example usage
if __name__ == "__main__":
    result = check_rdp("147.230.11.51", 3389, "admin", "admin", "")
    print(f"RDP check result: {result}")
```
