### ISSUE TITLE
Not suport IPV6  rdp_check.py

### ISSUE THREAD

**Issue by CptGuo** [fortra/impacket#1026]
### Configuration  
impacket version:  v0.9.22
Python version:  3
Target OS:  Ubuntu16

rdp_check Can't use ipv6 address

### Debug Output With Command String  
Traceback (most recent call last):
  File "rdpcheck", line 576, in <module>
    check_rdp(address, username, password, domain, options.hashes)
  File "rdpcheck", line 381, in check_rdp
    s.connect((host,3389))
socket.gaierror: [Errno -9] Address family for hostname not supported

**Comment by anadrianmanrique** [comment]
linked with #1811
