### ISSUE TITLE
Potential bug with latest commits

### ISSUE THREAD

**Issue by Bal0u** [fortra/impacket#1187]
### Configuration  
impacket version:  v0.9.23
Python version:  python3
Target OS:  Linux kali 4.19.0-kali5-amd64 #1 SMP Debian 4.19.37-1kali1 (2019-05-09) x86_64 GNU/Linux

### Debug Output With Command String  
python3 impacket/examples/ntlmrelayx.py
```
Impacket v0.9.23 - Copyright 2021 SecureAuth Corporation

[*] Protocol Client DCSYNC loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client SMB loaded..
[*] Running in reflection mode
Traceback (most recent call last):
  File "impacket/examples/ntlmrelayx.py", line 404, in <module>
    c = start_servers(options, threads)
  File "impacket/examples/ntlmrelayx.py", line 167, in start_servers
    c.setIsADCSAttack(options.adcs)
AttributeError: 'NTLMRelayxConfig' object has no attribute 'setIsADCSAttack'
```
### Additional context  
I tried with the last version just before the yesterday's commits, and it works fine:

```
/impacket-8c5eb3f53f9251400409cb59d6e3669ed084f032# python3 examples/ntlmrelayx.py
Impacket v0.9.23 - Copyright 2021 SecureAuth Corporation

[*] Protocol Client DCSYNC loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client SMTP loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client SMB loaded..
[*] Running in reflection mode
[*] Setting up SMB Server
[*] Setting up HTTP Server
[*] Setting up WCF Server

[*] Servers started, waiting for connections
```

Hope this helps :)

**Comment by Bal0u** [comment]
Works like a charm :)

Thanks and sorry for the hassle!
