### ISSUE TITLE
ntlmrelayx.py throwing errors

### ISSUE THREAD

**Issue by init5-SF** [fortra/impacket#1459]
### Configuration  
impacket version:  v0.10.0
Python version:  2.7.18
Target OS:  Linux kali 6.0.0-kali6-amd64

### Debug Output With Command String  
```
└─# ntlmrelayx.py -t 192.168.194.136 -c whoami -smb2support                                                                                                                               1 ⨯
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client DCSYNC loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client SMTP loaded..
[*] Running in relay mode to single host
Traceback (most recent call last):
  File "/usr/local/bin/ntlmrelayx.py", line 395, in <module>
    c = start_servers(options, threads)
  File "/usr/local/bin/ntlmrelayx.py", line 153, in start_servers
    c.setLDAPOptions(options.no_dump, options.no_da, options.no_acl, options.no_validate_privs, options.escalate_user, options.add_computer, options.delegate_access, options.dump_laps, options.dump_gmsa, options.sid)
TypeError: NTLMRelayxConfig.setLDAPOptions() missing 1 required positional argument: 'sid'
```

**Comment by 0xdeaddood** [comment]
Hi @init5-SF! It seems there is a mismatch version between the _ntlmrelayx_ script and the installed _Impacket library_ in your environment. Please take a look at: https://github.com/fortra/impacket#setup for a correct installation. On top of that, you are using a Python version that is no longer supported by Impacket.

Closing. Re-open if needed.

**Comment by Shiva108** [comment]
Got same issue.

**Comment by secfung** [comment]
Got the same issue. Python version is 3.11

**Comment by pwndside** [comment]
Got the same issue
