### ISSUE TITLE
GetUserSPNs.py not working as expected

### ISSUE THREAD

**Issue by init5-SF** [fortra/impacket#1466]
### Configuration  
impacket version:  0.10.0
Python version:  Python3
Target OS:  Kali

### Description
GetUserSPNs.py fails to get a ticket for kerberoastable users, it just shows the below error and exits

### Debug Output With Command String  

```
└─# GetUserSPNs.py 'LAB.ENTERPRISE.THM/nick:Passw0rd!' -dc-ip 10.10.33.222 -request -debug         
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

ServicePrincipalName  Name       MemberOf                                                     PasswordLastSet             LastLogon                   Delegation 
--------------------  ---------  -----------------------------------------------------------  --------------------------  --------------------------  ----------
HTTP/LAB-DC           bitbucket  CN=sensitive-account,CN=Builtin,DC=LAB,DC=ENTERPRISE,DC=THM  2021-03-12 03:20:01.333272  2021-04-26 17:16:41.570158             



[-] CCache file is not found. Skipping...
[+] The specified path is not correct or the KRB5CCNAME environment variable is not defined
[+] Using Kerberos Cache: None
Traceback (most recent call last):
  File "/usr/local/bin/GetUserSPNs.py", line 506, in <module>
    executer.run()
  File "/usr/local/bin/GetUserSPNs.py", line 366, in run
    TGT = self.getTGT()
  File "/usr/local/bin/GetUserSPNs.py", line 141, in getTGT
    creds = ccache.getCredential(principal)
AttributeError: 'NoneType' object has no attribute 'getCredential'
[-] 'NoneType' object has no attribute 'getCredential'
```

**Comment by 0xdeaddood** [comment]
Hi @init5-SF! There is a version mismatch between the Impacket library (v0.10.0) and the _GetUserSPNs_ script (v0.9.22). Please follow the [Setup](https://github.com/fortra/impacket/edit/master/README.md) section for a correct installation.

Closing. Re-open if needed.

**Comment by init5-SF** [comment]
Hello,

I have installed impacket correctly and now GetUserSPNs is showing a different error.
I've tried it against my home lab and against a TryHackMe machine and it shows the same error everywhere:

```
└─# GetUserSPNs.py 'LAB.ENTERPRISE.THM/nik:ToastyBoi!' -dc-ip 10.10.74.200 -request -debug
Impacket v0.10.1.dev1+20230116.181610.efcaec35 - Copyright 2022 Fortra

[+] Impacket Library Installation Path: /usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket
[+] Connecting to 10.10.74.200, port 389, SSL False
[+] Total of records returned 2
ServicePrincipalName  Name       MemberOf                                                     PasswordLastSet             LastLogon                   Delegation 
--------------------  ---------  -----------------------------------------------------------  --------------------------  --------------------------  ----------
HTTP/LAB-DC           bitbucket  CN=sensitive-account,CN=Builtin,DC=LAB,DC=ENTERPRISE,DC=THM  2021-03-12 03:20:01.333272  2021-04-26 17:16:41.570158             



[-] CCache file is not found. Skipping...
[+] The specified path is not correct or the KRB5CCNAME environment variable is not defined
[+] Trying to connect to KDC at 10.10.74.200
[+] Trying to connect to KDC at 10.10.74.200
[+] Trying to connect to KDC at LAB.ENTERPRISE.THM
[+] Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/krb5/kerberosv5.py", line 61, in sendReceive
    af, socktype, proto, canonname, sa = socket.getaddrinfo(targetHost, 88, 0, socket.SOCK_STREAM)[0]
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/EGG-INFO/scripts/GetUserSPNs.py", line 396, in run
    tgs, cipher, oldSessionKey, sessionKey = getKerberosTGS(principalName, self.__domain,
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/krb5/kerberosv5.py", line 438, in getKerberosTGS
    r = sendReceive(message, domain, kdcHost)
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/krb5/kerberosv5.py", line 65, in sendReceive
    raise socket.error("Connection error (%s:%s)" % (targetHost, 88), e)
OSError: [Errno Connection error (LAB.ENTERPRISE.THM:88)] [Errno -2] Name or service not known
[-] Principal: LAB.ENTERPRISE.THM\bitbucket - [Errno Connection error (LAB.ENTERPRISE.THM:88)] [Errno -2] Name or service not known
```
