### ISSUE TITLE
GetUserSPNs.py errors

### ISSUE THREAD

**Issue by init5-SF** [fortra/impacket#1468]
### Problem
Lates impacket version is installed, but GetUserSPNs.py isn't working properly, this has been tried against multiple different labs and I get the same result every time: [Errno -2] Name or service not known

### Configuration  
impacket version:  v0.10.1.dev1+20230116.181610.efcaec35
Python version:  3.10.9
Target OS:  Kali

### Debug Output With Command String  
```
└─# GetUserSPNs.py 'LAB.ENTERPRISE.THM/nik:ToastyBoi!' -dc-ip 10.10.74.200 -request -debug
Impacket v0.10.1.dev1+20230116.181610.efcaec35 - Copyright 2022 Fortra

[+] Impacket Library Installation Path: /usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket
[+] Connecting to 10.10.74.200, port 389, SSL False
[+] Total of records returned 2
ServicePrincipalName  Name       MemberOf                                                     PasswordLastSet             LastLogon                   Delegation 
--------------------  ---------  -----------------------------------------------------------  --------------------------  --------------------------  ----------
HTTP/LAB-DC           bitbucket  CN=sensitive-account,CN=Builtin,DC=LAB,DC=ENTERPRISE,DC=THM  2021-03-12 03:20:01.333272  2021-04-26 17:16:41.570158             



[-] CCache file is not found. Skipping...
[+] The specified path is not correct or the KRB5CCNAME environment variable is not defined
[+] Trying to connect to KDC at 10.10.74.200
[+] Trying to connect to KDC at 10.10.74.200
[+] Trying to connect to KDC at LAB.ENTERPRISE.THM
[+] Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/krb5/kerberosv5.py", line 61, in sendReceive
    af, socktype, proto, canonname, sa = socket.getaddrinfo(targetHost, 88, 0, socket.SOCK_STREAM)[0]
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/EGG-INFO/scripts/GetUserSPNs.py", line 396, in run
    tgs, cipher, oldSessionKey, sessionKey = getKerberosTGS(principalName, self.__domain,
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/krb5/kerberosv5.py", line 438, in getKerberosTGS
    r = sendReceive(message, domain, kdcHost)
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/krb5/kerberosv5.py", line 65, in sendReceive
    raise socket.error("Connection error (%s:%s)" % (targetHost, 88), e)
OSError: [Errno Connection error (LAB.ENTERPRISE.THM:88)] [Errno -2] Name or service not known
[-] Principal: LAB.ENTERPRISE.THM\bitbucket - [Errno Connection error (LAB.ENTERPRISE.THM:88)] [Errno -2] Name or service not known
```

**Comment by 0xdeaddood** [comment]
Hi @init5-SF!
Thanks for the report. There is an issue in the script when its trying to get the Service Ticket and the `-dc-ip` paramater is used. Please check this PR https://github.com/fortra/impacket/pull/1469 and let me know if it works.

**Comment by init5-SF** [comment]
Hi @0xdeaddood 
I managed to fix the issue by adding the domain name & ip to /etc/hostss
This seems to fix the issue. Thank you for your help!
