### ISSUE TITLE
psexec.py Silver Ticket Error

### ISSUE THREAD

**Issue by init5-SF** [fortra/impacket#1483]
Using psexec.py with a silver ticket fails for some reason, my impacket is up to date, so is my python.

### Configuration  
impacket version:  v0.10.1.dev1+20230116.181610.efcaec35
Python version:  3.10.9
Target OS:  Attacker: Linux kali 6.0.0-kali6-amd64 - Victim Domain Controller: Windows Server 2022 Datacenter

### Debug Output With Command String  
```
└─# psexec.py -k -no-pass bank.local/Administrator@dc.bank.local -debug                                                                                                                   1 ⨯
Impacket v0.10.1.dev1+20230116.181610.efcaec35 - Copyright 2022 Fortra

[+] Impacket Library Installation Path: /usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket
[+] StringBinding ncacn_np:dc.bank.local[\pipe\svcctl]
[+] Using Kerberos Cache: Administrator.ccache
[+] Returning cached credential for CIFS/DC.BANK.LOCAL@BANK.LOCAL
[+] Using TGS from cache
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/smbconnection.py", line 319, in kerberosLogin
    return self._SMBConnection.kerberosLogin(user, password, domain, lmhash, nthash, aesKey, kdcHost, TGT,
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/smb3.py", line 751, in kerberosLogin
    if ans.isValidAnswer(STATUS_SUCCESS):
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/smb3structs.py", line 458, in isValidAnswer
    raise smb3.SessionError(self['Status'], self)
impacket.smb3.SessionError: SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/EGG-INFO/scripts/psexec.py", line 123, in doStuff
    dce.connect()
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/dcerpc/v5/rpcrt.py", line 803, in connect
    return self._transport.connect()
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/dcerpc/v5/transport.py", line 514, in connect
    self.__smb_connection.kerberosLogin(self._username, self._password, self._domain, self._lmhash,
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.10.1.dev1+20230116.181610.efcaec35-py3.10.egg/impacket/smbconnection.py", line 322, in kerberosLogin
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)
[-] SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)
```
### Additional context  
Kali's time is sync'd with the DC, no time skew.

**Comment by 0xdeaddood** [comment]
Hi @init5-SF!

The `STATUS_MORE_PROCESSING_REQUIRED` error could mean many different things. How are you creating the silver ticket? Have you checked this: https://github.com/fortra/impacket/issues/1317?

**Comment by 0xdeaddood** [comment]
No answer, closing. Please re-open if needed.

**Comment by nuschpl** [comment]
Regardless of the exact problem original author faced, shouldn't this be properly handled with regards to 'During handling of the above exception, another exception occurred' and something more descriptive than 'cannot be disposed of because the I/O operation is not complete' ?  I believe fixing that kind of error doesn't need debugging specific case and appropriate error message instead of unhandled exception could help others facing similar issue in future
