### ISSUE TITLE
smbpasswd error：impacket.smbconnection.SessionError: SMB SessionError: STATUS_PASSWORD_EXPIRED

### ISSUE THREAD

**Issue by Dar1in9s** [fortra/impacket#1504]
### Configuration  
impacket version:  v0.10.1.dev1+20230203.111903.32178de
Python version:  Python 3.9.13
Target OS:  WIN2019

### Debug Output With Command String  

```
(base) root@ecs-104052:~/impacket/examples# proxychains ./smbpasswd.py WIN19/Adrian:babygirl1@172.22.4.45 -newpass admin123.
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
Impacket v0.10.1.dev1+20230203.111903.32178de - Copyright 2022 Fortra

[!] Password is expired, trying to bind with a null session.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/smbconnection.py", line 278, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash)
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/smb3.py", line 1040, in login
    if packet.isValidAnswer(STATUS_SUCCESS):
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/smb3structs.py", line 458, in isValidAnswer
    raise smb3.SessionError(self['Status'], self)
impacket.smb3.SessionError: SMB SessionError: STATUS_PASSWORD_EXPIRED(The user account password has expired.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/impacket/examples/./smbpasswd.py", line 254, in <module>
    smbpasswd.connect()
  File "/root/impacket/examples/./smbpasswd.py", line 78, in connect
    self.dce.connect()
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/dcerpc/v5/rpcrt.py", line 803, in connect
    return self._transport.connect()
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/dcerpc/v5/transport.py", line 512, in connect
    self.__smb_connection.login(self._username, self._password, self._domain, self._lmhash, self._nthash)
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/smbconnection.py", line 280, in login
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_PASSWORD_EXPIRED(The user account password has expired.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/smbconnection.py", line 278, in login
    return self._SMBConnection.login(user, password, domain, lmhash, nthash)
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/smb3.py", line 1040, in login
    if packet.isValidAnswer(STATUS_SUCCESS):
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/smb3structs.py", line 458, in isValidAnswer
    raise smb3.SessionError(self['Status'], self)
impacket.smb3.SessionError: SMB SessionError: STATUS_ACCESS_DENIED({Access Denied} A process has requested access to an object but has not been granted those access rights.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/impacket/examples/./smbpasswd.py", line 262, in <module>
    smbpasswd.connect(anonymous=True)
  File "/root/impacket/examples/./smbpasswd.py", line 78, in connect
    self.dce.connect()
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/dcerpc/v5/rpcrt.py", line 803, in connect
    return self._transport.connect()
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/dcerpc/v5/transport.py", line 512, in connect
    self.__smb_connection.login(self._username, self._password, self._domain, self._lmhash, self._nthash)
  File "/root/anaconda3/lib/python3.9/site-packages/impacket/smbconnection.py", line 280, in login
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_ACCESS_DENIED({Access Denied} A process has requested access to an object but has not been granted those access rights.)

```

### Additional context  
my now password is currect, but why i cannot change password successfully？

**Comment by 0xdeaddood** [comment]
Hi @Dar1in9s!

Have you checked that the $IPC share is accessible anonymously? The password you're trying to change is expired, so the script attempts a null session connection to modify it.

**Comment by 0xdeaddood** [comment]
No answer, closing. Please re-open if needed.
