### ISSUE TITLE
How to set "String Array" type variable when doing SpawnInstance()

### ISSUE THREAD

**Issue by XiaoliChan** [fortra/impacket#1514]
Hello guys, I want to know about how to pass "String Array" when doing SpawnInstance().

Here is an example:
```
firewall_PortClass,_ = iWbemServices.GetObject('MSFT_NetProtocolPortFilter')
#firewall_Instance = firewall_PortClass
firewall_Instance = firewall_PortClass.SpawnInstance()
firewall_Instance.CreationClassName = "fuckyouaasasasaasas"
firewall_Instance.Name = ""
firewall_Instance.SystemCreationClassName = ""
firewall_Instance.SystemName = ""
firewall_Instance.DynamicTransport=0
firewall_Instance.InstanceID="aasaoskljakjl"
firewall_Instance.LocalPort = [445]
firewall_Instance.Protocol="TCP"
firewall_Instance.RemotePort = ""
self.checkError(iWbemServices.PutInstance(firewall_Instance.marshalMe()))
```
In this case, `LocalPort` only accepts "String Array"

Got [-] E_FAIL - Unspecified error. after running this code

**Comment by XiaoliChan** [comment]
I also try to modify [wmi.py line 2434](https://github.com/fortra/impacket/blob/master/impacket/dcerpc/v5/dcom/wmi.py#L2434)
```
            if propRecord['type'] & CIM_ARRAY_FLAG:
                if itemValue is None:
                    ndTable |= self.__ndEntry(i, True, propIsInherited)
                    valueTable += pack(packStr, 0)
                else:
                    valueTable += pack('<L', curHeapPtr)
                    arraySize = pack(HEAPREF[:-2], len(itemValue))
                    packStrArray =  CIM_TYPES_REF[pType][:-2]
                    arrayItems = b''
                    for j in range(len(itemValue)):
                        if type(itemValue[j]) == str:
                            strIn = ENCODED_STRING()
                            strIn['Character'] = itemValue[j]
                            arrayItems += strIn.getData()
                        else:
                            arrayItems += pack(packStrArray, itemValue[j])
                            print(arrayItems)
                    instanceHeap += arraySize + arrayItems
                    curHeapPtr = len(instanceHeap)
```

But I still get unspecified error
```
Traceback (most recent call last):
  File "/home/xiaoli/wmiexec-RegOut-NEW/wrapper.py", line 60, in run
    executer_WINRM.WINRM_Wrapper('enable')
  File "/home/xiaoli/wmiexec-RegOut-NEW/lib/winrm.py", line 22, in WINRM_Wrapper
    self.configure_Firewall()
  File "/home/xiaoli/wmiexec-RegOut-NEW/lib/winrm.py", line 107, in configure_Firewall
    self.checkError(iWbemServices.PutInstance(firewall_Instance.marshalMe()))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/impacket/dcerpc/v5/dcom/wmi.py", line 3108, in PutInstance
    resp = self.request(request, iid = self._iid, uuid = self.get_iPid())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/impacket/dcerpc/v5/dcomrt.py", line 1329, in request
    resp = dce.request(req, uuid)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 859, in request
    answer = self.recv()
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/impacket/dcerpc/v5/rpcrt.py", line 1330, in recv
    raise DCERPCException('%s - %s' % (error_msg_short, error_msg_verbose))
impacket.dcerpc.v5.rpcrt.DCERPCException: E_FAIL - Unspecified error.
[-] E_FAIL - Unspecified error.
```
