### ISSUE TITLE
Can I connect to a Windows host on cloud by using impacket?

### ISSUE THREAD

**Issue by Flyzmx** [fortra/impacket#1539]
```
DEBUG:impacket:Target system is 10.200.xx.xx and isFQDN is False
DEBUG:impacket:StringBinding: \\\\WIN-S8J7JKNC1AV[\\PIPE\\atsvc]
DEBUG:impacket:StringBinding: \\\\WIN-S8J7JKNC1AV[\\pipe\\SessEnvPublicRpc]
DEBUG:impacket:StringBinding: WIN-S8J7JKNC1AV[49667]
DEBUG:impacket:StringBinding: 192.168.10.74[49667]
DEBUG:impacket:StringBinding chosen: None
Traceback (most recent call last):
  File "/root/zmx/test.py", line 13, in <module>
    iWbemServices = iWbemLevel1Login.NTLMLogin('\\\\%s\\root\\cimv2' % ip, NULL, NULL)
  File "/root/zmx/virtualenv3/lib/python3.9/site-packages/impacket/dcerpc/v5/dcom/wmi.py", line 3258, in NTLMLogin
    resp = self.request(request, iid = self._iid, uuid = self.get_iPid())
  File "/root/zmx/virtualenv3/lib/python3.9/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1326, in request
    self.connect(iid)
  File "/root/zmx/virtualenv3/lib/python3.9/site-packages/impacket/dcerpc/v5/dcomrt.py", line 1286, in connect
    raise Exception('Can\'t find a valid stringBinding to connect')
Exception: Can't find a valid stringBinding to connect

```
10.200.xx.xx is public ip，192.168.10.74 is a private ip, but it can't connect.
So I would like to ask if it is supported？

**Comment by anadrianmanrique** [comment]
Is that local ip private address exposed through port forwarding? this seems to be not related to a cloud scenario, but to a topology network  issue. Also this is related specially to dcom interface connection and not the hole impacket project. I suggest to rephrase the issue tittle to be more specific

**Comment by 0xdeaddood** [comment]
No answer, closing. Reopen if needed.

**Comment by anadrianmanrique** [comment]
also duplicated of https://github.com/fortra/impacket/issues/272
