### ISSUE TITLE
ntlmrelayx.py SOCKS option TypeError with socks5 on relaying

### ISSUE THREAD

**Issue by yesiamdollar** [fortra/impacket#1575]
### Configuration  
impacket version:  Impacket v0.10.0
Python version:  3.11
Target OS:  Kali Linux

### Debug Output With Command String  
ps : I've installed the latest release from `https://github.com/fortra/impacket/releases/download/impacket_0_10_0/impacket-0.10.0.tar.gz`
When using socks option from ntlmrelayx.py, there is an error when trying to use crackmapexec or any other tool with proxychains.
```bash
pc crackmapexec smb -u 'A.FOOR' -p '' -d DOMAIN 10.13.15.2
```
I got this error and I can't relay
```txt
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 55444)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3/dist-packages/impacket/examples/ntlmrelayx/servers/socksserver.py", line 286, in __init__
    socketserver.BaseRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3/dist-packages/impacket/examples/ntlmrelayx/servers/socksserver.py", line 322, in handle
    hostLength = unpack('!B',request['PAYLOAD'][0])[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'int'
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 55460)
Traceback (most recent call last):
  File "/usr/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3/dist-packages/impacket/examples/ntlmrelayx/servers/socksserver.py", line 286, in __init__
    socketserver.BaseRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/lib/python3/dist-packages/impacket/examples/ntlmrelayx/servers/socksserver.py", line 322, in handle
    hostLength = unpack('!B',request['PAYLOAD'][0])[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'int'
----------------------------------------
```

**Comment by anadrianmanrique** [comment]
I tried with the master branch version and I couldn't reproduce it. Can you provide more context about your configuration. Can you try the master branch version also ? thanks

**Comment by gjhami** [comment]
I have the same issue, here are the details

NTLMRelayx Host
- Hostname: ATTACKER.test.local
- IP: 192.168.86.59
- OS: Kali 6.6.9-1kali1 (2024-01-08)
- Python version: 3.11.7
- Impacket version: v0.11.0 installed using pipx
- Relay Command: `ntlmrelayx.py -t ws01.test.local -socks -smb2support -debug`

Authentication Sender (WS02.test.local)
- OS: Windows 10 Pro 22H2
- Build: 19045.3930
- Coercion Method: Enter `\\192.168.86.59\test` into file explorer

Authentication Target (WS01.test.local)
- OS: Windows 10 Pro 22H2
- Build: 19045.4170

1. Relay setup
![image](https://github.com/fortra/impacket/assets/11875826/463d0e49-04b9-46c7-82aa-ddf906190ee1)
2. Socks connection established
![image](https://github.com/fortra/impacket/assets/11875826/0693f179-3300-49fc-8fb3-6d3696c72cfd)
3. Validate proxychains config
![image](https://github.com/fortra/impacket/assets/11875826/f129873b-ab5f-460b-a60d-005e03552b5c)
4. Attempt smbclient connection using the socks proxy
![image](https://github.com/fortra/impacket/assets/11875826/be4908d3-f67b-42fa-b852-daf77611199a)
![image](https://github.com/fortra/impacket/assets/11875826/78beba5a-a190-4f44-8b96-f3f323525bb5)
5. Attempt secretsdump using the socks proxy
![image](https://github.com/fortra/impacket/assets/11875826/a6fba677-2d59-440b-a679-2f400ede3a26)
![image](https://github.com/fortra/impacket/assets/11875826/bb5c86d9-3449-46f8-9df7-d554dcc8ddb8)
6. Validate a successful relay is possible by specifying the attack directly with ntlmrelayx (no socks)
![image](https://github.com/fortra/impacket/assets/11875826/1f2184d7-f615-46b1-a9c4-d1a1060a06d0)

**Comment by yesiamdollar** [comment]
hello @gjhami , did you tried socks4 on proxychains ?

**Comment by gjhami** [comment]
@yesiamdollar sadly that didn't work either, but I think it is the expected behavior since ntlmrelayx states it will create a socks5 listener.

Setup NTLMRelayx Listener
![image](https://github.com/fortra/impacket/assets/11875826/71269f4d-16b2-432b-bdf4-6fff7f90d8f9)

Receive DA connection
![image](https://github.com/fortra/impacket/assets/11875826/33bb1090-0c7c-49e2-9ff6-f75738cd5c86)

Attempt to secretsdump using SOCKS proxy connection configured for SOCKS4
![image](https://github.com/fortra/impacket/assets/11875826/b6ac7d5b-0132-450d-9863-cf1e7d0e8f91)

Output in NTLMRelayx Window
![image](https://github.com/fortra/impacket/assets/11875826/1de59b0f-d20f-497c-a28a-a34ce41f3cd6)

**Comment by gjhami** [comment]
I tried downgrading to python 3.10, since I realized 3.11 isn't actually supported, via pyenv, but that did not resolve the error. The following changes did. I'm still not sure why others are not experiencing the same error or what the underlying cause of the type mismatch is.

1. Selecting an element of the byte string in request['PAYLOAD'] unexpectedly resulted in an int instead of a buffer of 1 byte on [line 326](https://github.com/fortra/impacket/blob/f8899e65f16c50b871863528d419cfb701a5a3e3/impacket/examples/ntlmrelayx/servers/socksserver.py#L326) of impacket/exampless/ntlmrelayx/servers/socksserver.py. Manually converting the int to a buffer of 1 byte as follows allowed NTLMRelayx to successfully perform this part of parsing the intended target and it no longer threw an exception.
```python
hostLength = unpack('!B',request['PAYLOAD'][0].to_bytes())[0]
```
2. NTLMRelayx still wasn't working because hostnames of targets passed via proxychains were interpreted as bytestrings instead of strings and therefore didn't match hosts for any existing socks connections that were stored as strings. Decoding the hostname parsed from the socks proxy connection on [line 327](https://github.com/fortra/impacket/blob/f8899e65f16c50b871863528d419cfb701a5a3e3/impacket/examples/ntlmrelayx/servers/socksserver.py#L327) of impacket/exampless/ntlmrelayx/servers/socksserver.py into a string as follows resolved this issue. 
```python
self.targetHost = request['PAYLOAD'][1:hostLength+1].decode(1, 'little')
```

---

Successful screenshots:
- An exception is still generated because 'no such domain exists' that warrants further troubleshooting, but this occurs during the NTDS dump portion of secretsdump which doesn't apply since I was targeting a workstation. The following screenshots show success with python3.10, but the same changes also allowed me to successfully perform secretsdump using a SOCKS connection for authentication with python3.11.

![image](https://github.com/fortra/impacket/assets/11875826/bc360ff8-0356-4d1c-8b4f-67076411c425)
![image](https://github.com/fortra/impacket/assets/11875826/142c3362-74ff-4b92-a034-4a0a99893ca0)
![image](https://github.com/fortra/impacket/assets/11875826/7fcc06b8-acd7-4f13-9614-61143b5226d3)

---

Failure with python3.10 without the changes described above:
![image](https://github.com/fortra/impacket/assets/11875826/d744edf9-be9f-4587-a56a-25a95109037a)
![image](https://github.com/fortra/impacket/assets/11875826/fccddcc3-7ef8-4994-913e-072fb1fca9f6)
![image](https://github.com/fortra/impacket/assets/11875826/591eb053-797f-4cc8-a1c3-4e0a0a1dafa7)

**Comment by gjhami** [comment]
Update: I just had the same issue in a client environment. If anyone has any advice or is getting the socks proxy feature to work correctly and could share OS/python/impacket versions that would be much appreciated! Thanks in advance!

**Comment by gjhami** [comment]
Update: I've attached screenshots and [pcaps.zip](https://github.com/user-attachments/files/17589784/pcaps.zip) for the loopback and ethernet interfaces that validate the issue persists in Impacktv0.12.0 using Python 3.12.0.

**WORKAROUND**: While the problem persists I did finally figure out how to make this work until the comprehensive solution described below is merged. If you use the hostname or FQDN of the target instead of the IP then it will result in the error posted here even though the attacker machine successfully resolves the FQDN to an IP as shown in eth0-capture-target-fqdn.pcap due to parsing issues with extracting the target from the command being proxied. However, if you just specify the IP of the target instead of the FQDN in both ntlmrelayx and the proxied command, then everything works as-is! This is still a bug and should be fixed, but at least there's a workaround for now and a solution below with a PR coming :)

## Environment Details:

NTLMRelayx Host (ATTACKER.test.local)
- IP: 192.168.86.59
- OS: Kali 6.11.2-kali1 (2024-10-15)
- Python version: 3.12.0
- Impacket version: v0.12.0 installed using pyenv
- Relay Commands:
  - FQDN Based: `ntlmrelayx.py -t ws01.test.local -socks -smb2support -debug`
  - IP Based: `ntlmrelayx.py -t 192.168.86.58 -socks -smb2support -debug`
- Secretsdump Commands:
  - FQDN Based: `proxychains -q secretsdump.py -debug -no-pass TEST/ADMINISTRATOR@ws01.test.local`
  - IP Based: `proxychains -q secretsdump.py -debug -no-pass TEST/ADMINISTRATOR@192.168.86.58`

Authentication Sender (WS02.test.local)
- IP: 192.168.86.60
- OS: Windows 10 Pro 22H2
- Build: 19045.5011
- Coercion Method: Enter `ls \\192.168.86.59\test123` into PowerShell

Authentication Target (WS01.test.local)
- IP: 192.168.86.58
- OS: Windows 10 Pro 22H2
- Build: 19045.5011

Domain Controller / DNS Server (DC01.test.local)
- IP: 192.168.86.57
- OS: Windows Server 2022 Standard 21H2
- Build: 20348.2340

## FQDN Based Screenshots
Relay
![image](https://github.com/user-attachments/assets/ae2447a6-8873-40c1-9864-485d36130b1b)
![image](https://github.com/user-attachments/assets/ccecf931-666a-4267-901a-d6171b8fa8ff)
![image](https://github.com/user-attachments/assets/238a7c24-5779-4436-a801-b86a7283dcd5)

Secretsdump
![image](https://github.com/user-attachments/assets/1283df42-6390-47b8-b8a9-212676a42981)

## IP Based Screenshots
Relay
- Notice there was a timeout error but this did not affect the success of secretsdump and I think it was just network related. It does not appear when debug mode is disabled.

![image](https://github.com/user-attachments/assets/16dd45d9-38db-4175-97e1-db8bd4ec2480)
![image](https://github.com/user-attachments/assets/a9925f08-7523-4d04-a4ec-0fa3e0b3fa93)
![image](https://github.com/user-attachments/assets/931d8c54-5429-457e-a47a-be9c56436559)

Secretsdump
![image](https://github.com/user-attachments/assets/1f9d37f5-2f3c-44a9-b50e-3d798500cc47)
![image](https://github.com/user-attachments/assets/0d348132-57e4-4562-9e99-54cf4b5bbc6c)

---

## Root Cause Analysis & Proposed Solution
The bug is triggered only when targeting by hostname or FQDN because of this codeblock from [Lines 321-332 of socksserver.py](https://github.com/fortra/impacket/blob/835e17550b57606ee3c681ae1c3f0edea096ec19/impacket/examples/ntlmrelayx/servers/socksserver.py#L321C1-L332C54)

```python
        # Let's process the request to extract the target to connect.
        # SOCKS5
        if self.__socksVersion == 5:
            if request['ATYP'] == ATYP.IPv4.value:
                self.targetHost = socket.inet_ntoa(request['PAYLOAD'][:4])
                self.targetPort = unpack('>H',request['PAYLOAD'][4:])[0]
            elif request['ATYP'] == ATYP.DOMAINNAME.value:
                hostLength = unpack('!B',request['PAYLOAD'][0])[0]
                self.targetHost = request['PAYLOAD'][1:hostLength+1]
                self.targetPort = unpack('>H',request['PAYLOAD'][hostLength+1:])[0]
            else:
                LOG.error('No support for IPv6 yet!')
```

Setting up some print statements for debugging showed the following:
```
request: 050100030f777330312e746573742e6c6f63616c01bd
request["ATYP"]: 3
request["PAYLOAD"]:  b'\x0fws01.test.local\x01\xbd'
request["PAYLOAD"][0]: 15
```

A little testing showed accessing the value at an index of a bytes object yielded an int, rather than another bytes object. Thanks for the surprise type conversion Python :).
![image](https://github.com/user-attachments/assets/f07ab3cd-0bcf-4ee5-beb7-666a54f82f80)

Removing the type conversion allowed execution to progress, but it subsequently interpreted the target passed by the proxied command as a bytes object instead of a string:
![image](https://github.com/user-attachments/assets/babd8fff-8000-4d91-9d71-3359f189511f)

A review of the git blame and PyPi history showed the code was introduced when python2.7 was still in use, and I confirmed the code would have been valid in Python2.7. It looks like it just never got updated to work with python3.
![image](https://github.com/user-attachments/assets/78fe4a97-7f3e-42c8-89b9-01138b6a510c)

## Fixed Code
 You could make the fix look nicer by just grabbing the 0th byte of the payload and expecting an int, but I chose to preserve the unpack behavior for the hostname length since byte order remains explicit this way.

```python
        # Let's process the request to extract the target to connect.
        # SOCKS5
        if self.__socksVersion == 5:
            if request['ATYP'] == ATYP.IPv4.value:
                self.targetHost = socket.inet_ntoa(request['PAYLOAD'][:4])
                self.targetPort = unpack('>H',request['PAYLOAD'][4:])[0]
            elif request['ATYP'] == ATYP.DOMAINNAME.value:
                hostLength = unpack('!B',request['PAYLOAD'][:1])[0]
                self.targetHost = request['PAYLOAD'][1:hostLength+1].decode(encoding='utf-8')
                self.targetPort = unpack('>H',request['PAYLOAD'][hostLength+1:])[0]
            else:
                LOG.error('No support for IPv6 yet!')
```

Decoding the bytes object for target name resolved this issue as well, so my [original solution](https://github.com/fortra/impacket/issues/1575#issuecomment-2036144159) was correct and I was just thrown off by the erroneous error shown in debug mode. I will make a PR for this. Checking git blame, it appears this feature has worked this way since the addition of the socks proxy functionality, so I'm not sure why more people aren't running into this.
