### ISSUE TITLE
Problem with getst.py spn in Chinese

### ISSUE THREAD

**Issue by helloyw** [fortra/impacket#1595]
### Configuration  
impacket version:  v0.11.0
Python version:  python3.10.5
Target OS:  windows

### Debug Output With Command String  
i.e.  
python3 getst.py -dc-ip 192.168.1.1 -spn host/'admin-中文.test.com' -imersonate Administrator test.com/test$:1qaz@WSX
```
Traceback (most recent call last):
  File "/home/kali/Desktop/impacket-0.11.0/examples/getST.py", line 655, in run
    tgs, cipher, oldSessionKey, sessionKey = self.doS4U(tgt, cipher, oldSessionKey, sessionKey, unhexlify(self.__nthash), self.__aesKey, self.__kdcHost)
  File "/home/kali/Desktop/impacket-0.11.0/examples/getST.py", line 422, in doS4U
    r = sendReceive(message, self.__domain, kdcHost)
  File "/usr/local/lib/python3.10/dist-packages/impacket-0.11.0-py3.10.egg/impacket/krb5/kerberosv5.py", line 91, in sendReceive
    raise krbError
impacket.krb5.kerberosv5.KerberosError: Kerberos SessionError: KDC_ERR_C_PRINCIPAL_UNKNOWN(Client not found in Kerberos database)
[-] Kerberos SessionError: KDC_ERR_C_PRINCIPAL_UNKNOWN(Client not found in Kerberos database)

```

### Additional context  
Cannot find this computer when getst.py spn is in Chinese

**Comment by XiaoliChan** [comment]
I believe these Chinese charters cause some `Latin-1` encoding issues.

**Comment by helloyw** [comment]
> 



> 我相信这些中国宪章会导致一些`Latin-1`编码问题。

师傅有办法解决吗？
Is there a solution?

**Comment by XiaoliChan** [comment]
Add `-debug` to print whole errors.
