### ISSUE TITLE
I'm having this problem with ntlmrelayx  __import__(package + '.' + os.path.splitext(file)[0])  import pyreadline as readline from . import logger, clipboard, lineeditor, modes, console

### ISSUE THREAD

**Issue by Shimon03** [fortra/impacket#1688]
┌──(kurn㉿read)-[/usr/share/doc/python3-impacket/examples]
└─$ ntlmrelayx.py 
Impacket v0.12.0.dev1+20231130.165011.d370e63 - Copyright 2023 Fortra

[*] Protocol Client DCSYNC loaded..
[*] Protocol Client RPC loaded..
[*] Protocol Client IMAP loaded..
[*] Protocol Client IMAPS loaded..
[*] Protocol Client MSSQL loaded..
[*] Protocol Client LDAPS loaded..
[*] Protocol Client LDAP loaded..
[*] Protocol Client SMB loaded..
[*] Protocol Client HTTP loaded..
[*] Protocol Client HTTPS loaded..
[*] Protocol Client SMTP loaded..
Traceback (most recent call last):
  File "/usr/local/bin/ntlmrelayx.py", line 417, in <module>
    from impacket.examples.ntlmrelayx.attacks import PROTOCOL_ATTACKS
  File "/home/kali/.local/lib/python3.11/site-packages/impacket/examples/ntlmrelayx/attacks/__init__.py", line 56, in <module>
    __import__(package + '.' + os.path.splitext(file)[0])
  File "/home/kali/.local/lib/python3.11/site-packages/impacket/examples/ntlmrelayx/attacks/smbattack.py", line 23, in <module>
    from impacket.examples.smbclient import MiniImpacketShell
  File "/home/kali/.local/lib/python3.11/site-packages/impacket/examples/smbclient.py", line 40, in <module>
    import pyreadline as readline
  File "/home/kali/.local/lib/python3.11/site-packages/pyreadline/__init__.py", line 12, in <module>
    from . import logger, clipboard, lineeditor, modes, console
  File "/home/kali/.local/lib/python3.11/site-packages/pyreadline/clipboard/__init__.py", line 13, in <module>
    from .win32_clipboard import GetClipboardText, SetClipboardText
  File "/home/kali/.local/lib/python3.11/site-packages/pyreadline/clipboard/win32_clipboard.py", line 39, in <module>
    from pyreadline.keysyms.winconstants import CF_UNICODETEXT, GHND
  File "/home/kali/.local/lib/python3.11/site-packages/pyreadline/keysyms/__init__.py", line 24
    raise ImportError("Could not import keysym for local pythonversion", x)
                                                                           ^
IndentationError: unindent does not match any outer indentation level

**Comment by anadrianmanrique** [comment]
try to remove **pyreadline** as it is not intended to be used in **linux** environments. Also **pyreadline** is not supported in _python_ > 3.5, as mentioned in https://github.com/fortra/impacket/pull/1681.
So by removing **pyreadline**, code will fallback into **readline** and work ok.
Thanks

**Comment by Shimon03** [comment]
@anadrianmanrique Sorry, when you say remove do you mean uninstall the  pyreadline?

**Comment by anadrianmanrique** [comment]
yes, by removing pyreadline I meant , uninstall the package

**Comment by anadrianmanrique** [comment]
linked with #1800
