### ISSUE TITLE
impacket.nmb.NetBIOSTimeout: The NETBIOS connection with the remote host timed out.

### ISSUE THREAD

**Issue by eamanu** [fortra/impacket#1824]
### Configuration  
impacket version:  HEAD
Python version:  
Target OS:  Debian sid

During the test execution we have this kind of errors:

```
 SimpleSMBServerFuncTests.test_smbserver_connect_disconnect_tree ________________________________________________________________________________________________________

self = <impacket.nmb.NetBIOSTCPSession object at 0x7f9149e7b0e0>, read_length = 4, timeout = 60

    def non_polling_read(self, read_length, timeout):
        data = b''
        if timeout is None:
            timeout = 3600
    
        start_time = time.time()
        bytes_left = read_length
    
        while bytes_left > 0:
            self._sock.settimeout(timeout)
            try:
>               received = self._sock.recv(bytes_left)
E               TimeoutError: timed out

impacket/nmb.py:986: TimeoutError

During handling of the above exception, another exception occurred:

self = <tests.SMB_RPC.test_smbserver.SimpleSMBServerFuncTests testMethod=test_smbserver_connect_disconnect_tree>

    def test_smbserver_connect_disconnect_tree(self):
        """Test connecting/disconnecting to a share tree.
        """
        server = self.get_smbserver()
        self.start_smbserver(server)
    
>       client = self.get_smbclient()

tests/SMB_RPC/test_smbserver.py:327: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/SMB_RPC/test_smbserver.py:227: in get_smbclient
    smbclient = SMBConnection(self.address, self.address, sess_port=int(self.port),
impacket/smbconnection.py:82: in __init__
    self.negotiateSession(preferredDialect)
impacket/smbconnection.py:122: in negotiateSession
    packet = self.negotiateSessionWildcard(self._myName, self._remoteName, self._remoteHost, self._sess_port,
impacket/smbconnection.py:182: in negotiateSessionWildcard
    resp = self._nmbSession.recv_packet(timeout)
impacket/nmb.py:917: in recv_packet
    data = self.__read(timeout)
impacket/nmb.py:1004: in __read
    data = self.read_function(4, timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <impacket.nmb.NetBIOSTCPSession object at 0x7f9149e7b0e0>, read_length = 4, timeout = 60

    def non_polling_read(self, read_length, timeout):
        data = b''
        if timeout is None:
            timeout = 3600
    
        start_time = time.time()
        bytes_left = read_length
    
        while bytes_left > 0:
            self._sock.settimeout(timeout)
            try:
                received = self._sock.recv(bytes_left)
            except socket.timeout:
>               raise NetBIOSTimeout
E               impacket.nmb.NetBIOSTimeout: The NETBIOS connection with the remote host timed out.

impacket/nmb.py:988: NetBIOSTimeout
----------------------------------------------------------------------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------------------------------------------------------------------
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/eamanu/Debian/impacket/upstream/impacket/impacket/smbserver.py", line 4909, in start
    self.__srvsServer.start()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/threading.py", line 973, in start
    _start_joinable_thread(self._bootstrap, handle=self._handle,
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                           daemon=self.daemon)
                           ^^^^^^^^^^^^^^^^^^^
RuntimeError: thread already started
=========================================================================================================================== short test summary info ============================================================================================================================
FAILED tests/SMB_RPC/test_smbserver.py::SimpleSMBServerFuncTests::test_smbserver_connect_disconnect_tree - impacket.nmb.NetBIOSTimeout: The NETBIOS connection with the remote host timed out.
```

To reproduce it I run:
```
tox -e py3.13 -- tests/SMB_RPC/test_smbserver.py
```

I tried to figure out the issue but I couldn't.

Original reported here [0]

[0] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1082142

**Comment by anadrianmanrique** [comment]
Hello, thanks for reporting! We are not supporting offically 3.13 at the moment. Anyway, we plan to do it in the short term, so this report it's useful. We will keep you updated as soon as we can get more details about the issue. Thanks!

**Comment by eamanu** [comment]
Hi @anadrianmanrique,

Thanks for the response. I will patch out these tests to avoid break the Py3.13 transition.

I will keep my eyes here to avoid ignore this issue.

cheers!

**Comment by anadrianmanrique** [comment]
Ok, after a quick check I was able to reproduce the issue on debian sid ( after installing python3.13-full package )

**Comment by anadrianmanrique** [comment]
Setting this one as **low**, as the issue seems to be related to how the usage of _multiprocessing.Process_ instance at https://github.com/fortra/impacket/blob/27e7e7478df5d3d3bb12923055a7d8b614825ff4/tests/SMB_RPC/test_smbserver.py#L234. The test is actually falling due to the SMBserver process being stuck for some reason ( it happens only in python3.13 ). I did a quick test replacing _multiprocessing.Process_ for **threading.Thread** and test is passing.

**Comment by anadrianmanrique** [comment]
Ok, I was just able to isolate the problem. It seems there's an issue in python3.13, were starting a _threading.Thread_ object (instantiated in the parent process) in the context of the parent process.
The following code triggers an exception in 3.13 but not in 3.12:

```
from multiprocessing import Process
from threading import Thread
import time
class MyThread(Thread):
    def __init__(self):
        Thread.__init__(self)
        self.__data = 'ttest'

    def run(self):
        print(self.__data)


class Aclass():
    def __init__(self):
        self._t = MyThread()
        self._t.daemon=True
    def start(self):
        self._t.start()
        print("thread started")

if __name__ == '__main__':
    t = Aclass()
    p = Process(target = t.start )
    p.start()
    time.sleep(2)
```

**Comment by anadrianmanrique** [comment]
For the record, I filled an issue in cpython project https://github.com/python/cpython/issues/134381

**Comment by anadrianmanrique** [comment]
@eamanu I just merged a temporary fix for the **smbserver** tesetcases. That fix will be evaluated to be removed once the patch for 3.13 gets backported.
Thank you!
