### ISSUE TITLE
SSL WantRead error in tds.py

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [fortra/impacket#827]
### Configuration  
impacket version:  Impacket v0.9.22.dev1+20200327.103853.7e505892
Python version:  3.7
Target OS:  Windows Server 2003 R2 SP2

### Debug Output With Command String  
i.e.  
mssqlclient.py domain/user@host -hashes <hash> -debug
```
[+] Impacket Library Installation Path: /home/tacticaldevc/.local/lib/python3.7/site-packages/impacket
[*] Encryption required, switching to TLS
[+] Exception:
Traceback (most recent call last):
  File "/home/tacticaldevc/.local/lib/python3.7/site-packages/impacket/tds.py", line 917, in login
    tls.do_handshake()
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1622, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tacticaldevc/.local/bin/mssqlclient.py", line 179, in <module>
    res = ms_sql.login(options.db, username, password, domain, options.hashes, options.windows_auth)
  File "/home/tacticaldevc/.local/lib/python3.7/site-packages/impacket/tds.py", line 921, in login
    tds = self.recvTDS()
  File "/home/tacticaldevc/.local/lib/python3.7/site-packages/impacket/tds.py", line 606, in recvTDS
    packet = TDSPacket(self.socketRecv(packetSize))
  File "/home/tacticaldevc/.local/lib/python3.7/site-packages/impacket/structure.py", line 84, in __init__
    self.fromString(data)
  File "/home/tacticaldevc/.local/lib/python3.7/site-packages/impacket/structure.py", line 149, in fromString
    self[field[0]] = self.unpack(field[1], data[:size], dataClassOrCode = dataClassOrCode, field = field[0])
  File "/home/tacticaldevc/.local/lib/python3.7/site-packages/impacket/structure.py", line 382, in unpack
    return unpack(format, data)[0]
struct.error: ('unpack requires a buffer of 1 bytes', "When unpacking field 'Type | <B | b''[:1]'")
[-] ('unpack requires a buffer of 1 bytes', "When unpacking field 'Type | <B | b''[:1]'")
```

### PCAP  
No PCAP

### Additional context  
This error might occur due to the target using an ancient SSL/TLS version (1.0). Using MSFs aux module no error occurs.

**Comment by vincd** [comment]
I had a similar issue and I get around by changing the `Encryption` value in [`tds.py` on lines 514-515](https://github.com/SecureAuthCorp/impacket/blob/master/impacket/tds.py#L515) :

```python
prelogin['Encryption'] = TDS_ENCRYPT_NOT_SUP
#prelogin['Encryption'] = TDS_ENCRYPT_OFF
```

I had no time to investigate the issue. MSF seems to use the value `TDS_ENCRYPT_NOT_SUP` in [their implementation](https://github.com/rapid7/metasploit-framework/blob/76954957c740525cff2db5a60bcf936b4ee06c42/lib/metasploit/framework/mssql/client.rb#L582) that why there is no issue with their client.

**Comment by tacticalDevC** [comment]
Thank you :)

**Comment by anadrianmanrique** [comment]
this should be fixed at least, after #2122. please reopen if needed. thanks
